agent:
  collection_jitter: 0s
  flush_interval: 10s
  flush_jitter: 0s
  hostname: ''
  interval: 10s
  metric_batch_size: 1000
  metric_buffer_limit: 10000
  omit_hostname: false
  precision: ''
  round_interval: true
global_tags: {}
inputs:
  cpu:
  - collect_cpu_time: false
    percpu: true
    report_active: false
    totalcpu: true
  disk:
  - ignore_fs:
    - tmpfs
    - devtmpfs
    - devfs
    - iso9660
    - overlay
    - aufs
    - squashfs
  diskio:
  - {}
  kernel:
  - {}
  mem:
  - {}
  processes:
  - {}
  swap:
  - {}
  system:
  - {}
outputs:
  influxdb:
  - {}
